spring:
  application:
    name: dataseeder
  main:
    web-application-type: none

services:
  product:
    url: http://localhost:8080
  order:
    url: http://localhost:8080
  payment:
    url: http://localhost:8080
  user:
    url: http://localhost:8080
